#!/usr/bin/env python3
"""YuJian Experience Manager: validate registry and build deterministic views."""

from __future__ import annotations
import argparse
import html
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "design" / "registry" / "experience_registry_v1.json"
MARKDOWN = ROOT / "design" / "registry" / "EXPERIENCE_STATUS.md"
HTML = ROOT / "design" / "manager" / "index.html"

STATUSES = {"FROZEN","ACTIVE_CLOSURE","PARTIAL","RUNTIME_ONLY","DESIGN_ONLY","MISSING","DEPRECATED"}
MODS = ["behavior","visual","motion","haptic","sound","runtime","evidence"]
ICON = {"FROZEN":"✅","ACTIVE_CLOSURE":"🟡","PARTIAL":"🟠","RUNTIME_ONLY":"🔵","DESIGN_ONLY":"🟣","MISSING":"❌","DEPRECATED":"⚫"}


def load():
    try:
        data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read registry: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("registry root must be an object")
    return data


def validate(data):
    errors = []
    if set(data.get("status_vocabulary", [])) != STATUSES:
        errors.append("status_vocabulary does not match governance vocabulary")
    features = data.get("features")
    if not isinstance(features, list):
        return errors + ["features must be a list"]

    seen = set()
    for i, feature in enumerate(features):
        if not isinstance(feature, dict):
            errors.append(f"features[{i}] must be an object")
            continue
        fid = feature.get("id")
        if not isinstance(fid, str) or not fid:
            errors.append(f"features[{i}].id is invalid")
            continue
        if fid in seen:
            errors.append(f"duplicate feature id: {fid}")
        seen.add(fid)
        if feature.get("overall") not in STATUSES:
            errors.append(f"{fid}: invalid overall status")
        if not isinstance(feature.get("owner_path"), str):
            errors.append(f"{fid}: owner_path is invalid")
        modalities = feature.get("modalities")
        if not isinstance(modalities, dict):
            errors.append(f"{fid}: modalities must be an object")
            continue
        for mod in MODS:
            entry = modalities.get(mod)
            if not isinstance(entry, dict):
                errors.append(f"{fid}: missing modality {mod}")
                continue
            status = entry.get("status")
            if status not in STATUSES:
                errors.append(f"{fid}/{mod}: invalid status {status!r}")
            authority = entry.get("authority")
            if authority is None:
                if status == "FROZEN":
                    errors.append(f"{fid}/{mod}: FROZEN requires authority")
            elif not isinstance(authority, str) or not authority:
                errors.append(f"{fid}/{mod}: invalid authority")
            elif not (ROOT / authority).exists():
                errors.append(f"{fid}/{mod}: authority does not exist: {authority}")
    return errors


def markdown(data):
    features = data["features"]
    counts = Counter(f["overall"] for f in features)
    lines = [
        "# YuJian Experience Status",
        "",
        "> AUTO-GENERATED by scripts/experience_manager.py build.",
        "> Update experience_registry_v1.json and feature contracts instead of editing this file.",
        "",
        f"Registry version: **{data.get('version','unknown')}**  ",
        f"Features: **{len(features)}**  ",
        "Overall: " + " · ".join(f"{ICON.get(k,'')} {k} {v}" for k,v in sorted(counts.items())),
        "",
        "## Feature matrix",
        "",
        "| Feature | Overall | Behavior | Visual | Motion | Haptic | Sound | Runtime | Evidence |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for f in features:
        row = [f["id"], f"{ICON.get(f['overall'],'')} {f['overall']}"]
        for mod in MODS:
            s = f["modalities"][mod]["status"]
            row.append(f"{ICON.get(s,'')} {s}")
        lines.append("| " + " | ".join(row) + " |")

    lines += ["", "## Gaps / active closure", ""]
    found = False
    for f in features:
        items = []
        for mod in MODS:
            s = f["modalities"][mod]["status"]
            if s != "FROZEN":
                items.append(f"{mod}={s}")
        if items or f["overall"] != "FROZEN":
            found = True
            lines.append(f"- **{f['id']}** — overall {f['overall']}; " + ", ".join(items))
    if not found:
        lines.append("- None.")
    lines += ["", "## Commands", "", "    python3 scripts/experience_manager.py validate", "    python3 scripts/experience_manager.py summary", "    python3 scripts/experience_manager.py build", ""]
    return "\n".join(lines)


def dashboard(data):
    payload = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    icons = json.dumps(ICON, ensure_ascii=False)
    mods = json.dumps(MODS)
    version = html.escape(str(data.get("version","unknown")))
    return f"""<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>YuJian Experience Manager</title>
<style>
body{{margin:0;background:#f4f7f6;color:#173238;font-family:Inter,system-ui,sans-serif}}
header{{padding:24px 28px;background:white;border-bottom:1px solid #dde6e3;position:sticky;top:0}}
h1{{margin:0 0 4px;font-size:23px}} .sub,.path{{color:#71858a;font-size:12px}}
.controls{{display:flex;gap:8px;margin-top:14px}} input,select{{padding:9px 11px;border:1px solid #cfdad7;border-radius:10px;background:white}}
main{{padding:20px 28px 40px}} .stats{{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}}
.stat,.card{{background:white;border:1px solid #dde6e3;border-radius:13px}} .stat{{padding:8px 10px;font-size:12px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:12px}} .card{{padding:14px}}
.card h2{{font-size:15px;margin:0}} .badge{{font-size:10px;background:#eef3f2;border-radius:99px;padding:4px 7px}}
.mods{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:12px}} .mod{{border:1px solid #edf1f0;border-radius:9px;padding:7px;min-width:0}}
.name{{font-size:10px;color:#71858a;text-transform:capitalize}} .status{{font-size:11px;font-weight:700;margin-top:2px}}
.path{{overflow-wrap:anywhere;margin-top:3px}} .note{{font-size:11px;color:#5c7075;background:#f8faf9;padding:8px;border-radius:9px;margin-top:10px}}
</style></head><body>
<header><h1>YuJian Experience Manager</h1><div class="sub">Registry v{version} · Behavior / Visual / Motion / Haptic / Sound / Runtime / Evidence</div>
<div class="controls"><input id="q" placeholder="搜索模块…"><select id="filter"><option value="">全部状态</option></select></div></header>
<main><div id="stats" class="stats"></div><div id="grid" class="grid"></div></main>
<script>
const data={payload}; const icon={icons}; const mods={mods};
const q=document.getElementById("q"), filter=document.getElementById("filter"), grid=document.getElementById("grid"), stats=document.getElementById("stats");
[...new Set(data.features.map(f=>f.overall))].sort().forEach(s=>{{const o=document.createElement("option");o.value=s;o.textContent=s;filter.appendChild(o)}});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}})[c]);
function render(){{
 const term=q.value.trim().toLowerCase(); const selected=filter.value;
 const list=data.features.filter(f=>(!selected||f.overall===selected)&&(!term||JSON.stringify(f).toLowerCase().includes(term)));
 const count={{}}; data.features.forEach(f=>count[f.overall]=(count[f.overall]||0)+1);
 stats.innerHTML='<div class="stat"><b>'+data.features.length+'</b> modules</div>'+Object.keys(count).sort().map(k=>'<div class="stat">'+(icon[k]||"")+' '+esc(k)+' <b>'+count[k]+'</b></div>').join("");
 grid.innerHTML=list.map(f=>'<article class="card"><h2>'+esc(f.id)+' <span class="badge">'+(icon[f.overall]||"")+' '+esc(f.overall)+'</span></h2><div class="path">'+esc(f.owner_path)+'</div><div class="mods">'+mods.map(m=>{{const x=f.modalities[m];return '<div class="mod"><div class="name">'+esc(m)+'</div><div class="status">'+(icon[x.status]||"")+' '+esc(x.status)+'</div>'+(x.authority?'<div class="path">'+esc(x.authority)+'</div>':"")+'</div>'}}).join("")+'</div>'+(f.note?'<div class="note">'+esc(f.note)+'</div>':"")+'</article>').join("");
}}
q.addEventListener("input",render);filter.addEventListener("change",render);render();
</script></body></html>"""


def build(data):
    MARKDOWN.parent.mkdir(parents=True, exist_ok=True)
    HTML.parent.mkdir(parents=True, exist_ok=True)
    MARKDOWN.write_text(markdown(data), encoding="utf-8")
    HTML.write_text(dashboard(data), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="YuJian Experience Manager")
    parser.add_argument("command", choices=["validate","summary","build"])
    args = parser.parse_args()
    try:
        data = load()
    except ValueError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    errors = validate(data)
    if errors:
        for error in errors:
            print("ERROR " + error, file=sys.stderr)
        print(f"FAIL: {len(errors)} registry issue(s)", file=sys.stderr)
        return 1
    if args.command == "validate":
        print(f"PASS: registry valid; {len(data['features'])} features")
    elif args.command == "summary":
        print(markdown(data))
    else:
        build(data)
        print("PASS: generated experience status and dashboard")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
